# ============================================================
#  DATABASE MODELS - All tables for crypto bot
# ============================================================

from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Text, 
    Boolean, JSON, DECIMAL, ForeignKey, Index
)
from sqlalchemy.sql import func
from src.core.database import Base


class PriceData(Base):
    """OHLCV price data for all symbols"""
    __tablename__ = 'price_data'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    timeframe = Column(String(10), nullable=False)
    
    open = Column(DECIMAL(20, 8))
    high = Column(DECIMAL(20, 8))
    low = Column(DECIMAL(20, 8))
    close = Column(DECIMAL(20, 8))
    volume = Column(DECIMAL(20, 8))
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        Index('idx_price_symbol_timeframe', 'symbol', 'timestamp', 'timeframe'),
        Index('idx_price_timestamp', 'timestamp'),
    )


class IndicatorValues(Base):
    """All calculated indicator values"""
    __tablename__ = 'indicator_values'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    timeframe = Column(String(10), nullable=False)
    
    # Trend indicators
    ema_9 = Column(DECIMAL(20, 8))
    ema_21 = Column(DECIMAL(20, 8))
    ema_50 = Column(DECIMAL(20, 8))
    ema_200 = Column(DECIMAL(20, 8))
    supertrend = Column(DECIMAL(20, 8))
    supertrend_direction = Column(String(10))
    adx = Column(DECIMAL(10, 4))
    
    # Momentum indicators
    rsi_14 = Column(DECIMAL(10, 4))
    macd = Column(DECIMAL(20, 8))
    macd_signal = Column(DECIMAL(20, 8))
    macd_hist = Column(DECIMAL(20, 8))
    wavetrend = Column(DECIMAL(10, 4))
    wavetrend_signal = Column(DECIMAL(10, 4))
    
    # Volatility indicators
    bb_upper = Column(DECIMAL(20, 8))
    bb_middle = Column(DECIMAL(20, 8))
    bb_lower = Column(DECIMAL(20, 8))
    atr_14 = Column(DECIMAL(20, 8))
    
    # Volume indicators
    vwap = Column(DECIMAL(20, 8))
    obv = Column(DECIMAL(20, 8))
    volume_spike = Column(DECIMAL(10, 2))
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        Index('idx_indicator_symbol_timeframe', 'symbol', 'timestamp', 'timeframe'),
    )


class MarketData(Base):
    """Market data: funding rates, liquidations, order book"""
    __tablename__ = 'market_data'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    
    funding_rate = Column(DECIMAL(10, 6))
    funding_rate_8h = Column(DECIMAL(10, 6))
    liquidation_1h_usd = Column(DECIMAL(20, 2))
    liquidation_24h_usd = Column(DECIMAL(20, 2))
    bid_ask_ratio = Column(DECIMAL(10, 4))
    spread = Column(DECIMAL(10, 4))
    depth_imbalance = Column(DECIMAL(10, 4))
    
    open_interest = Column(DECIMAL(20, 2))
    open_interest_value = Column(DECIMAL(20, 2))
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        Index('idx_market_symbol_time', 'symbol', 'timestamp'),
    )


class Signal(Base):
    """Trading signals generated by strategies"""
    __tablename__ = 'signals'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    timeframe = Column(String(10), nullable=False)
    
    total_score = Column(DECIMAL(5, 2))
    confidence = Column(String(10))
    
    # Individual strategy scores
    trend_score = Column(DECIMAL(5, 2))
    breakout_score = Column(DECIMAL(5, 2))
    ma_crossover_score = Column(DECIMAL(5, 2))
    mean_reversion_score = Column(DECIMAL(5, 2))
    smc_score = Column(DECIMAL(5, 2))
    
    # Signal details
    direction = Column(String(10))
    entry_price = Column(DECIMAL(20, 8))
    stop_loss = Column(DECIMAL(20, 8))
    take_profit = Column(DECIMAL(20, 8))
    signal_data = Column(JSON)
    
    # ===== FIBONACCI LEVELS =====
    fib_entry_zone = Column(DECIMAL(20, 8))
    fib_stop_loss = Column(DECIMAL(20, 8))
    fib_tp1 = Column(DECIMAL(20, 8))
    fib_tp2 = Column(DECIMAL(20, 8))
    fib_tp3 = Column(DECIMAL(20, 8))
    fib_support = Column(DECIMAL(20, 8))
    fib_resistance = Column(DECIMAL(20, 8))
    fib_retrace_382 = Column(DECIMAL(20, 8))
    fib_retrace_500 = Column(DECIMAL(20, 8))
    fib_retrace_786 = Column(DECIMAL(20, 8))
    fib_swing_high = Column(DECIMAL(20, 8))
    fib_swing_low = Column(DECIMAL(20, 8))
    fib_range = Column(DECIMAL(20, 8))
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        Index('idx_signal_symbol_time', 'symbol', 'timestamp'),
        Index('idx_signal_score', 'total_score'),
    )


class BacktestResult(Base):
    """Backtest performance results"""
    __tablename__ = 'backtest_results'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_name = Column(String(50), nullable=False)
    symbol = Column(String(20), nullable=False)
    timeframe = Column(String(10), nullable=False)
    
    start_date = Column(DateTime(timezone=True))
    end_date = Column(DateTime(timezone=True))
    
    total_trades = Column(Integer)
    win_rate = Column(DECIMAL(5, 2))
    profit_factor = Column(DECIMAL(10, 4))
    total_return = Column(DECIMAL(10, 4))
    sharpe_ratio = Column(DECIMAL(10, 4))
    max_drawdown = Column(DECIMAL(10, 4))
    
    parameters = Column(JSON)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Alert(Base):
    """Alerts sent via Telegram"""
    __tablename__ = 'alerts'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, ForeignKey('signals.id'))
    symbol = Column(String(20), nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    
    message = Column(Text)
    sent_to_telegram = Column(Boolean, default=False)
    viewed = Column(Boolean, default=False)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        Index('idx_alert_symbol_time', 'symbol', 'timestamp'),
    )


class OnChainData(Base):
    """On-chain data for cryptocurrencies"""
    __tablename__ = 'onchain_data'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20), nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False)
    
    score = Column(DECIMAL(5, 2))
    direction = Column(String(10))
    confidence = Column(String(10))
    
    whale_score = Column(DECIMAL(5, 2))
    whale_direction = Column(String(10))
    accumulation_score = Column(DECIMAL(5, 2))
    accumulation_direction = Column(String(10))
    network_score = Column(DECIMAL(5, 2))
    network_direction = Column(String(10))
    
    details = Column(JSON)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        Index('idx_onchain_symbol_time', 'symbol', 'timestamp'),
    )